# Generated by Django 4.2.3 on 2023-07-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_files',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
