# Generated by Django 4.2.3 on 2023-07-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_uploadimage_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_files',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
