# Generated by Django 4.2.3 on 2023-07-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_upload_files_alter_uploadimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
