# Generated by Django 4.2.3 on 2023-07-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
