# Generated by Django 4.2.3 on 2023-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_comment'),
        ('user', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
