# Generated by Django 4.2.3 on 2023-07-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_options_and_more'),
        ('user', '0003_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_views',
            field=models.ManyToManyField(to='blog.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='guest_ztvOnWqz', max_length=50, unique=True),
        ),
    ]
