# Generated by Django 4.2.3 on 2023-07-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='guest_mGIuhFnY', max_length=50, unique=True),
        ),
    ]
