# Generated by Django 4.2.3 on 2023-07-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_log_user'),
        ('user', '0010_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='guest_97636291', max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_views',
        ),
        migrations.AddField(
            model_name='user',
            name='post_views',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
