# Generated by Django 4.2.3 on 2023-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_log_user'),
        ('user', '0011_alter_user_name_remove_user_post_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='guest_70595476', max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_views',
        ),
        migrations.AddField(
            model_name='user',
            name='post_views',
            field=models.ManyToManyField(to='blog.post'),
        ),
    ]
